build: resolve missing header inclusion
For completeness, do not forget to include appropriate headers.
Otherwise, this can hypothetically ensue:

loop-linux.c:93:3: warning: implicit declaration of function "signed_cast"
loop-linux.c:101:3: warning: implicit declaration of function "HX_strdup"