build: resolve compile error on ehd_keydec_request
The error was:

crypto.c: In function 'ehd_kdreq_new':
crypto.c:522:24: error: dereferencing pointer to incomplete type

And was a result of the ehd_keydec_request structure not being defined
at all when openssl was not enabled.